drop table if exists Travel;
create table Travel
( TravelID int unsigned not null auto_increment primary key,
Rank int(2),
Location varchar(50),
Why text
);
insert into Travel values (NULL,1,"London","London is a world unto itself. The eclectic neighborhoods which house a blend of historical landmarks and modernday attractions can keep you occupied for days. Visit the Tower of London and the British Museum or explore Portobello Road and Borough Market.");
insert into Travel values (NULL,2,"Bora Bora","It's hard not to be enchanted by this paradisiacal destination: Lush jungles extend into sky high volcanoes and sands stretch into upscale resorts. When you're not relaxing on the beach, carve out some time for hiking Mount Otemanu or observing aquatic life at the Bora Bora Lagoonarium.");
insert into Travel values (NULL,3,"Barcelona","Though known for its fútbol team, Barcelona boasts much more than athletic talent. The city is a feast for the eyes: Visitors walk past medieval architecture in the Barri Gòtic and Gaudi's innovative creations at Parc Güell. Meanwhile, Las Ramblas buzzes at all hours.");
insert into Travel values (Null,4,"Paris","Year after year, the magnetic City of Light draws travelers looking to cross the Eiffel Tower and Notre Dame off their bucket lists. But what visitors really fall in love with are Paris' quaint cafes, vibrant markets, trendy shopping districts and unmistakable je ne sais quoi charm.");
insert into Travel values (Null,5,"Sydney","This metropolis offers more than just a dizzying array of landmarks (e.g., the Opera House and the Sydney Harbour Bridge). Sydney boasts a warm, sunny climate ideal for enjoying the city's beaches. The sands at Coogee and Bondi draw locals and tourists alike.");
insert into Travel values (Null,6,"New York City","New York City hosts infinite urban adventures: Wander through Central Park, tour the exhibits at the Met, catch a Broadway show or peruse SoHo's stylish boutiques. And at night, admire Manhattan's glittering skyscrapers from the top of the Empire State Building.");
insert into Travel values (Null,7,"Maui","Maui one of the most beloved of all the Hawaiian Islands lives up to its superlatives with exotic beaches (like Kaihalulu), palatial resorts (like the Four Seasons Resort Maui at Wailea) and lush terrain (as seen in the Iao Valley State Park).");
insert into Travel values (Null,8,"Rio de Janeiro","As the upcoming host of the 2016 Olympic Games, Rio is arguably South America's hottest destination and not just for its warm weather. The famous Christ the Redeemer statue presides over Copacabana Beach. And you'll be hardpressed to find a livelier event than Rio's Carnival.");
insert into Travel values (Null,9,"Cape Town","This South African city appeals to adventure seekers and mellow travelers alike. Kickstart your day by climbing Table Mountain. Afterward, sunbathe along Clifton Beach's khakicolored sands or tour the vineyards of the Constantia Valley.");
insert into Travel values (Null,10,"San Fransisco","Gourmet restaurants, funky boutiques and laidback vibes are just some of San Fran's charms. A ride on the cable cars and a visit to Alcatraz are musts. And, of course, don't forget to visit the city's crowning architectural achievement the Golden Gate Bridge.");
insert into Travel values (Null,11,"Maldives","The simple mention of the Maldives conjures images of blue waters and soft sands. This collection of more than 1,000 islands boasts unparalleled resorts and pristine beaches. Visitors say the islands' allures are difficult to comprehend unless you see them for yourself.");
insert into Travel values (Null,12,"Prague","Prague has transitioned from a backpacker secret to a flourishing Eastern European capital. The narrow streets lead to iconic landmarks such as the Charles Bridge and St. Vitus Cathedral. Save some time for enjoying local pilsners on a bar crawl.");
insert into Travel values (Null,13,"Yellowstone"," More than 3,000 square miles of nature's finest canyons, geysers and rocky cliffs are an easy sell for outdoors enthusiasts. Geothermic wonders like the Mammoth Hot Springs, Old Faithful and Yellowstone Lake are not to be missed at this national park.");
insert into Travel values (Null,14,"Bahamas","The Bahamas comprises so many islands that it's hard to mash them all into one recommendation. But that's also part of their appeal. Airfare and hotel rates are reasonable throughout the year, but you'll get the best deals if you visit in the summer or early fall.");
insert into Travel values (Null,15,"Vancouver","Vancouver may not be as grand as Toronto or as historic as Montreal, but it's no mystery why this Canadian city regularly hosts international sporting events. The city bursts with parks, galleries and outdoor activities.");
insert into Travel values (Null,16,"Washington D.C.","One of the mostvisited cities in the U.S., our nation's capital houses a trove of iconic monuments. Exploring the White House, the Lincoln Memorial and the Smithsonian Museums can fill several days. And the best part is: Everything's free to visit.");
insert into Travel values (Null,17,"U.S. Virgin Islands","A visit to the USVI will feel like an international vacation (Carnival and reggae music) with a taste of home (U.S. dollars and no language barrier). But you won't find beaches like this on the mainland. For the best rates and weather, visit in late spring.");
insert into Travel values (Null,18,"Zurich","From swimming in Lake Zurich in the summer to skiing the Alps in the winter, Zurich attracts visitors yearround. Delectable pastry shops abound, as do museums, churches and shops in Bahnhofstrasse. At night, check out the bars in edgy Zurich West.");
insert into Travel values (Null,19,"Budapest","Budapest is a sure standout for any trip to Eastern Europe. The city caters to a wide range of traveler types and budgets with its variety of hotels and restaurants. The city will keep you occupied with its thermal baths and worldclass museums.");
insert into Travel values (Null,20,"Las Vegas","America's Playground offers plenty of entertainment day or night. Neonlit casinos, like the Bellagio and Caesar's Palace, beckon to travelers with fascinating shows and sprawling game floors. Plus, these megaresorts boast spas, pools, upscale rooms and diverse restaurants.");
insert into Travel values (Null,21,"Hong Kong","Hong Kong is worth visiting for its one of a kind cultural fusion. Only here will you find a Disney theme park rubbing elbows with ancient temples. Peruse a street market, ride the Star Ferry from Tsim Sha Tsui pier or check out the views from atop Victoria Peak.");
insert into Travel values (Null,22,"Crete","Crete's diverse landscape is speckled with ancient ruins, fragrant olive groves and gorgeous beaches. Visitors can spend their days doing anything from shopping in Agios Nikolaos to hiking the Samaria Gorge before noshing on fresh fish at one of the island's lively tavernas.");
insert into Travel values (Null,23,"Playa del Carmen","People flock to this town along the Yucatán Peninsula to unwind along whitesand beaches and azure waters. With the lively La Quinta Avenida parallel to the beach, travelers don't have to venture far to find entertainment.");
insert into Travel values (Null,24,"Puerto Rico","Meander along cobbled streets and admire historic sites like El Morro in Old San Juan. Prefer miles of sand? Consider the bioluminescent bays of Culebra and Vieques. For a vibrant night scene, visit the Isla Verde or Santurce neighborhoods of San Juan.");
insert into Travel values (Null,25,"Jurusalem","Many travelers seek out Jerusalem for its ancient ties to Judaism, Christianity and Islam. Pack your visit to the city with stops at religious and historic sites, such as the Western Wall, Temple Mount and the Church of the Holy Sepulchre.");